### PR TITLE
Refactor: fix header mediaquery

### LINKED ISSUE #7: Header menu on tablet viewports
Between 768 and ~850 px width the header menu items wrap breaking the UI.

Image

### PR DESCRIPTION
**Pull request by MarcoJul**
### 🔗 Linked issue

Closes #7 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This change fix the header menu breakpoint issue in the tablet-size area.
It also moves the header component from the layout file to a dedicated one.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by TheJoin95 — APPROVED** [review]
Seems legit, if you'd like, you can add a playwright test

**Comment by Readpato** [comment]
Super nice @MarcoJul, thanks for the PR 🫶

I'll review it properly tomorrow since I see there are some things we can improve before merging :)

File: src/frontend/components/Header.vue [hunk 1]
```diff
@@ -0,0 +1,229 @@
+<script setup lang="ts">
+import { onMounted, onUnmounted, ref, watch } from 'vue'
+import { useRouter } from 'vue-router'
```
Comment (Readpato) [inline src/frontend/components/Header.vue:3]: You can actually remove these imports since they are [auto-imported with Nuxt](https://nuxt.com/docs/4.x/guide/concepts/auto-imports)

File: src/frontend/components/Header.vue [hunk 2]
```diff
@@ -0,0 +1,229 @@
...
+  >
+    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
+      <div class="flex items-center justify-between h-16">
+        <!-- Logo -->
+        <NuxtLink to="/" class="flex items-center gap-2">
+          <img
+            src="/certo-logo-text.png"
+            alt="Certo logo"
+            class="h-10 w-auto"
+          />
```
Comment (Readpato) [inline src/frontend/components/Header.vue:105]: We should utilize the `<NuxtImg />` component here so we can streamline all of our images that we utilize in our app

You can see how to utilize it over here in the [HomeTrustees.vue](https://github.com/MarcoJul/certo/blob/63521596f96b0f3c24eac73b7c9008614053873b/src/frontend/components/home/HomeTrustees.vue#L11)

File: src/frontend/constants/index.ts [hunk 3]
```diff
@@ -3,3 +3,11 @@
  */
 
 export const WEBSITE_URL = 'https://certo.schroedinger-hat.org'
+
+export const headerNavLinks = [
```
Comment (Readpato) [inline src/frontend/constants/index.ts:7]: Let's rename this to `HEADER_NAV_LINKS` to maintain the constants naming in sync with the others

File: src/frontend/layouts/default.vue [hunk 4]
```diff
@@ -1,237 +1,12 @@
...
-}
-
-const navLinks = [
-  { name: 'Home', href: '/' },
-  { name: 'About', href: '/about' },
-  { name: 'Dashboard', href: '/dashboard' },
-  { name: 'Issue Badges', href: '/issue' },
-  { name: 'Verify', href: '/verify' }
-]
+import Header from '~/components/Header.vue'
```
Comment (Readpato) [inline src/frontend/layouts/default.vue:3]: You don't need to import components as they are automatically imported in[Nuxt](https://nuxt.com/docs/4.x/guide/directory-structure/app/components)

**Comment by TheJoin95** [comment]
@MarcoJul yep ref https://github.com/Schroedinger-Hat/certo/tree/main/src/frontend/e2e

**Review by Readpato — APPROVED** [review]
